name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.58.209.137
          username: dennisdo440
          key: ${{ secrets.VM_DEPLOY_KEY }}
          script: ~/bulletin/scripts/deploy.sh
