name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.30.218.223
          username: dennisnasa
          key: ${{ secrets.VM_DEPLOY_KEY }}
          script: bash ~/bulletin/scripts/deploy.sh
